# Animation
animations=1
layer_animations=1

# Types
animation_type_open=zoom
animation_type_close=zoom

# Directions
tag_animation_direction=0

# Zoom
zoom_initial_ratio=0.6
zoom_end_ratio=0.8

# Fade
animation_fade_in=1
fadein_begin_opacity=0.5
animation_fade_out=1
fadeout_begin_opacity=0.5

# Duration
animation_duration_move=150
animation_duration_focus=150
animation_duration_open=350
animation_duration_close=350
animation_duration_tag=250

# Curves
animation_curve_move=0.46,1.0,0.29,1
animation_curve_focus=0.46,1.0,0.29,1
animation_curve_open=0.46,1.0,0.29,1
animation_curve_close=0.46,1.0,0.29,1
animation_curve_tag=0.46,1.0,0.29,1
