# Reload config
bind=SUPER,r,reload_config

# Exit
bind=SUPER,m,quit
bind=SUPER,q,killclient

# Menu and terminal
bind=SUPER+CTRL,l,spawn,swaylock
bind=SUPER,Return,spawn,foot
bind=SUPER,p,spawn,fuzzel
bind=SUPER,b,spawn,~/.config/scripts/bg-picker.sh

# Layout
bind=SUPER,o,toggleoverview,
bind=SUPER,v,togglefloating,
bind=SUPER,f,switch_proportion_preset,
bind=SUPER+SHIFT,f,togglefullscreen,

# Windows
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down

bind=SUPER+CTRL,Up,exchange_client,up
bind=SUPER+CTRL,Down,exchange_client,down
bind=SUPER+CTRL,Left,exchange_client,left
bind=SUPER+CTRL,Right,exchange_client,right

# Tags
bind=SUPER,Page_Up,viewtoleft
bind=SUPER,Page_Down,viewtoright

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

# Monitors
bind=SUPER+SHIFT,Left,focusmon,left
bind=SUPER+SHIFT,Right,focusmon,right
bind=SUPER+SHIFT+CTRL,Left,tagmon,left
bind=SUPER+SHIFT+CTRL,Right,tagmon,right

# Mouse binds
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_middle,togglemaximizescreen,
mousebind=SUPER,btn_right,moveresize,curresize

axisbind=SUPER,UP,viewtoleft
axisbind=SUPER,DOWN,viewtoright
axisbind=SUPER+SHIFT,UP,focusdir,left
axisbind=SUPER+SHIFT,DOWN,focusdir,right