# Scroller
scroller_structs=20
scroller_default_proportion=0.8
scroller_focus_center=0
scroller_prefer_center=0
edge_scroller_pointer_focus=0
edge_scroller_focus_allow_speed=0.0
scroller_default_proportion_single=1.0
scroller_proportion_preset=1.0,0.8,0.5

# Overview
ov_tab_mode=0
ov_no_resize=1
enable_hotarea=0
hotarea_size=10
