# Opacity
focused_opacity=1.0
unfocused_opacity=1.0

# Gaps
gappih=5
gappiv=5
gappoh=10
gappov=10
overviewgappi=5
overviewgappo=30

# Borders
borderpx=4
border_radius=0

# Blur
blur=0
blur_layer=0

# Shadows
shadows=0
layer_shadows=0
