# Tag
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller

# Layer
layerrule=layer_name:launcher,animation_type_open:zoom
layerrule=layer_name:launcher,animation_type_close:zoom
layerrule=layer_name:notifications,shield_when_capture:1

# Window
windowrule=appid:org.keepassxc.KeePassXC,shield_when_capture:1
windowrule=appid:firefox,title=work — Mozilla Firefox,shield_when_capture:1
windowrule=appid:thunderbird,shield_when_capture:1
windowrule=appid:Emacs,scroller_proportion:1.0
